bookings/urls.py
from . import views 
from django.urls import path


urlpatterns = [
    path('', views.Index, name='index'),
    path('inspiration/', views.Inspiration.as_view(), name='photos'),
    path('prices/', views.PriceList, name='prices'),
    path('appointment_bookings/', views.new_appointment, name="appointment_bookings"),
    path('my_appointments/', views.BookingList, name="my_appoints"),
    path('edit/<booking_id>', views.EditBooking, name="edit"),
    path('delete/<booking_id>', views.DeleteBooking, name="delete"),
]

hannahs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookings.urls'), name='bookings_urls'),
    # above is given the name of 'bookings_urls and is for all urls in the bookings folder"
    path('accounts/', include('allauth.urls')),
]

bookings/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from datetime import datetime


class Photo(models.Model):
    featured_image = CloudinaryField('image', default='placeholder')
    

class Appointments(models.Model):
    """Contains info about appointment"""

    class Meta:
        unique_together = ('nail_tech', 'date', 'timeslot')

    TIMESLOT_LIST = (
        (0, '9am - 9.45am'),
        (1, '9.45am - 10.30am'),
        (2, '10.30am - 11.15am'),
        (3, '11.15am - 12pm'),
        (4, '12.30pm - 1.15pm'),
        (5, '1.15pm - 2pm'),
        (6, '2pm - 2.45pm'), 
        (7, '2.45pm - 3.30pm'),
        (8, '3.30pm - 4.15pm'),
        (7, '4.15pm - 5pm'),
    )

    nail_tech = models.ForeignKey('Technician',on_delete = models.CASCADE)
    date = models.DateField(help_text="YYYY-MM-DD")
    timeslot = models.IntegerField(choices=TIMESLOT_LIST)
    phone_number = models.CharField(max_length=20, blank=True, null=True, help_text="Required")
    user = models.ForeignKey(User, default='', null=True, on_delete=models.CASCADE,)

    def __str__(self):
        return '{} {} {}. Patient: {}'.format(self.date, self.timeslot, self.nail_tech, self.user, self.phone_number,)

    @property
    def time(self):
        return self.TIMESLOT_LIST[self.timeslot][1]


class Technician(models.Model):
    """Stores info about doctor"""

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    def __str__(self):
        return '{}'.format(self.short_name)

    @property
    def short_name(self):
        return '{} {}.'.format(self.last_name.title(), self.first_name[0].upper())
   

bookings/forms.py
from datetime import date

from django import forms
from datetimewidget.widgets import DateTimeWidget

from .models import Appointments


class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointments
        fields = ('nail_tech', 'date', 'timeslot', 'phone_number')
        widgets = {
            'date': forms.DateInput(
                attrs={'type': 'date'}
                ),
        }

    def clean_date(self):
        day = self.cleaned_data['date']

        if day <= date.today():
            raise forms.ValidationError('Date should be upcoming (tomorrow or later)', code='invalid')
        if day.isoweekday() in (1, 7):
            raise forms.ValidationError("Sorry! We are closed on a Sunday and a Monday", code='invalid')

        return day

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from .models import Photo, Appointments
from .forms import AppointmentForm
from django.contrib import messages



def Index(request):
    # The View function for index/home page of site
    template_name = "index.html"
    context = {}
    return render(request, 'index.html', context=context)


class Inspiration(generic.ListView):
    # The View function for inspiration page of site
    model = Photo
    template_name = 'inspiration.html'



def PriceList(request):
    # The View function for index/home page of site
    template_name = "index.html"
    context = {}
    return render(request, 'prices.html', context=context)


def new_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            # The above line automatically adds the logged in users name to the back end booking when an appointment is made. 
            obj.save()
            messages.add_message(request, messages.SUCCESS, 'Your appointment has been made. Thank you.')
            return redirect('/')
        else:
            messages.add_message(request, messages.ERROR, 'Your appointment was not made, Please try again.')
    else:
        form = AppointmentForm()
    return render(request, 'appointment_bookings.html', {'form': form})


def BookingList(request):
    # function bring over booking details from admin site.
    booking_list = Appointments.objects.all().filter(user=request.user).order_by('date')
    return render(request, 'my_appointments.html', {'booking_list': booking_list})


def EditBooking(request, booking_id):
    booking = get_object_or_404(Appointments, id=booking_id)
    form = AppointmentForm(instance=booking)

    # Post handler
    if request.method == 'POST':
        form = AppointmentForm(request.POST, instance=booking)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            # The above line automatically adds the logged in users name to the back end booking when an appointment is made. 
            obj.save()
            messages.add_message(request, messages.SUCCESS, 'Your appointment has been changed. Thank you.')
            return redirect('/')
        else:
            messages.add_message(request, messages.ERROR, 'Your appointment was not changed, Please try again.')
        
    return render(request, 'edit_booking.html', {'form': form})


def DeleteBooking(request, booking_id):
    booking = get_object_or_404(Appointments, id=booking_id)
    messages.add_message(request, messages.SUCCESS, 'Your appointment has been deleted. Thank you.')
    booking.delete()

    return redirect('/')

templates/appointment_bookings.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags  %}


{% if user.is_authenticated %}

<div style="height: 50px;"></div>

<div class="container-fluid appointments-title">
    <div class="row">
        <h3>Get booked in!</h3>
    </div>
</div>

<div class="container appointment-container">
    <div class="">
        <form method="post" class="appointment-form" style="text-align: center;">
            {{ form | crispy}}
            {% csrf_token %}

            <button type="submit" class="btn btn-primary" style="margin-top: 30px;">Save</button>
            <br>
            <button type="reset" class="btn btn-default" style="margin-top: 30px;">Reset</button>
        </form>
        <a href="{% url 'my_appoints' %}" type="button" class="btn btn-outline-secondary page-button"
            style="margin-top: 30px;">My Appointments
        </a>
    </div>
</div>

{% endif %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <script src="https://kit.fontawesome.com/e24716021f.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Playfair+Display&display=swap" rel="stylesheet">
  <meta name="description" content="Hannah's Nail Bar website">
  <meta name="keywords"
    content="Hannahs nail saoln, nails, nail extensions, acrylics, nail acrylics, nail bar, auchterarder, perthshire, nail gels, nail art.">
  <meta name="author" content="Steve Miller, Miller Creative">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Hannahs Nail Bar</title>
</head>

<body>

  <nav class="navbar fixed-top" style="background-color: rgba(255,255,255, 0.3);">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}"><img
          src="https://res.cloudinary.com/millermayhem/image/upload/v1653850658/nav_logo_vtza1e.png"
          alt="Hannahs Nail Bar Logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
        aria-controls="offcanvasNavbar" aria-label="navigation-toggle-button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Hannahs Nail Bar</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'photos' %}">Inspiration</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'prices' %}">Prices</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'appointment_bookings' %}">Book An
                Appointment</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'my_appoints' %}">My Appointments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert" style="z-index: 999999;">
          {{ message | safe }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>


  <!-- BLOCK CONTENT -->
  <main class="flex-shrink-0 main-bg">
    {% block content %}

    {% endblock content %}
  </main>


  <!-- Footer -->
  <footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on socials:</span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a href="https://www.facebook.com" target="_blank" aria-label="Visit our facebook (opens in a new tab)"
          class="me-4 text-reset" style="text-decoration: none;">
          <i class="fab fa-facebook socials"></i>
        </a>
        <a href="https://www.tiktok.com/en/" target="_blank" aria-label="Visit our tiktok (opens in a new tab)"
          class="me-4 text-reset" style="text-decoration: none;">
          <i class="fab fa-tiktok socials"></i>
        </a>
        <a href="https://www.instagram.com" target="_blank" aria-label="Visit our instagram (opens in a new tab)"
          class="me-4 text-reset" style="text-decoration: none;">
          <i class="fab fa-instagram socials"></i>
        </a>

      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="black-text">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class=""></i>Hannah's Nail Bar
            </h6>
            <p>
              Perthshire's favourite creative nails in the heart of Auchterarder.

            </p>
          </div>
          
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="{% url 'index' %}" class="text-reset" style="text-decoration: none;">Home</a>
            </p>
            <p>
              <a href="{% url 'photos' %}" class="text-reset" style="text-decoration: none;">Inspiration</a>
            </p>
            <p>
              <a href="{% url 'account_login' %}" class="text-reset" style="text-decoration: none;">Login</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> 76 High St, Auchterarder PH3 1BN</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              nails@hannahsnailbar.com
            </p>
            <p><i class="fas fa-phone me-3"></i> 01764 66 00 68</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      <p>Copyright &copy; <script>
          document.write(new Date().getFullYear())
        </script> Hannah's Nail Bar All Rights Reserved</p>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
  </script>
  <script>
    setTimeout(function () {
        let messages = document.getElementById('msg');
        let alert = new bootstrap.Alert(messages);
        alert.close();
    }, 2500);
</script>

</body>

</html>

templates/edit_booking.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags  %}


{% if user.is_authenticated %}

<div style="height: 50px;"></div>

<div class="container-fluid appointments-title">
    <div class="row">
        <h3>Get booked in!</h3>
    </div>
</div>

<div class="container appointment-container">
    <div class="">
        <form method="post" class="appointment-form" style="text-align: center;">
            {{ form | crispy}}
            {% csrf_token %}
            <td>
                <button type="submit" class="btn btn-primary" style="margin-top: 30px;">Update Booking</button>
            </td>
            <br>
            <td>
                <button type="reset" class="btn btn-default" style="margin-top: 30px;">Reset</button>
            </td>
        </form>
        <a href="{% url 'my_appoints' %}">
            <button type="button" class="btn btn-outline-secondary page-button" style="margin-top: 30px;">My
                Appointments</button>
        </a>
    </div>
</div>

{% endif %}

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="bg-image d-flex justify-content-center align-items-center cover-image" style="
    background-image: url('https://res.cloudinary.com/millermayhem/image/upload/v1654785469/Background_1_70web_usnvki.jpg');
    height: 100vh;">

    <div class="container hello-g">
        <div class="row">
            <div class="col">
                <p>Hello<br>Gorgeous</p>
            </div>
            {% if user.is_authenticated %}
            <div class="col" style="text-align:center; padding-top: 50px;">
                <button onclick="location.href='{% url 'appointment_bookings' %}'" type="button"
                        class="btn btn-outline-secondary open-sans text-dark book-button">Appointments</button>
            </div>
            {% else %}
            <div class="col" style="text-align:center; padding-top: 50px;">
                <button onclick="location.href='{% url 'account_login' %}'" type="button"
                        class="btn btn-outline-secondary open-sans text-dark book-button">Member Login</button>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<!-- About the salon-->

<div class="container">
    <div class="row">
        <div class="col info-title">
            The Sanctuary
        </div>
    </div>

    <div class="row">
        <div class="col info-section">
            <p>
                Set in the heart of Auchterarders High Street, Hannah's Nail Bar has a city meets small town vibe!
                When opening the salon I knew I wanted to create a fun, welcoming space for all clients. From friendly
                chat, to the bright & airy surroundings, to the pick & mix... not forgetting the catchiest playlists.
                I love all things nail art and never shy away from an intricate challenge. Once I'm in the creative zone
                there are no limits!
            </p>
            <p>
                Since opening in 2019 I have been lucky enough to have seen a great number of locals and visitors alike.
                Whatever your circumstances you are always welcome at my little slice of nail heaven.
                My doors are open Tuesdays to Saturdays so please feel free to get in touch. <br>
                See you soon!
            </p>
        </div>
    </div>
</div>

<!-- thumbnails photos -->

<div style="text-align: center;">
    <div class="col thumbnail-container">
        <span style="display: inline"><img class="thumbnail"
                src="https://res.cloudinary.com/millermayhem/image/upload/v1654783205/salon-4web_ynqvtb.jpg"
                alt="External image of salon"></span>
        <span style="display: inline"><img class="thumbnail"
                src="https://res.cloudinary.com/millermayhem/image/upload/v1654783205/salon-2web_ni5mdr.jpg"
                alt="Internal image of salon"></span>
        <span style="display: inline"><img class="thumbnail"
                src="https://res.cloudinary.com/millermayhem/image/upload/v1654783205/salon-3web_afzlpz.jpg"
                alt="Internal image of salon"></span>
        <span style="display: inline"><img class="thumbnail"
                src="https://res.cloudinary.com/millermayhem/image/upload/v1654783205/salon-1web_o4vzdb.jpg"
                alt="Internal image of salon"></span>
    </div>
</div>

<!-- about hannah -->

<div class="container" style="padding: 40px;">
    <div class="row">
        <div class="col-sm hannah-hello" style="font-size: 70px;">
            <p>"Hello<br>beautiful<br>people"</p>
        </div>
        <div class="col-sm bg-image d-flex hannah-image"
            style="
              background-image: url('https://res.cloudinary.com/millermayhem/image/upload/v1653950516/Hannah_for_web_fndlju.jpg'); object-fit: contain;"></div>
        <div class="col-sm info-section">
            Hi, I'm Hannah, owner of Hannah's Nail Bar! <br>
            After completing my training in 2012 at the Scottish Beauty School
            in Hillington Glasgow, and working alongside my mum in her hair salon, I decided to follow in her footsteps
            and open a salon of my own. <br>
            My love for the industry and business has gone from strength to stregnth and continues
            to do so while also growing my career. Hopefully I'll see you soon in my little nail sanctuary.

        </div>
    </div>
</div>

<div style="height: 50px;"></div>

{% endblock %}

templates/inspiration.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col memory-title">
      Memory book...
    </div>
  </div>
</div>

<div class="container gallery">
  <div class="row">

    <div class="col-12 mt-3 left">
      <div class="row">
        <!-- Loops through photos in list of photos -->
        {% for photo in photo_list %}

        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
              <div class="image-container">
                {% if "placeholder" in photo.featured_image.url %}
                <img
                  src="https://res.cloudinary.com/millermayhem/image/upload/v1653982722/Gallery_Placeholder_rjvxg5.jpg"
                  alt="">
                {% else %}
                <img class="card-img-top" src="{{ photo.featured_image.url }}" alt="">
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <!-- if statement to make photos display in rows of 3 -->
        {% if forloop.counter|divisibleby:3 %}
      </div>
      <div class="row">
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/my_appointments.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags  %}


{% if user.is_authenticated %}

<div style="height: 100px;"></div>

<div class="container-fluid appointments-title">
    <div class="row">
        <h3>My Appointments</h3>
    </div>
</div>

<div class="container-fluid">
    <div class="row">

        <!-- Booking Cards Generated -->
        <div class="col-12 mt-1 justify-content-center">
            <div class="row">

                {% for booking in booking_list %}
                <div class="col-md-auto center">
                    <div class="appointment-container ">
                        <div class="card" style="width: 20em;">
                            <img src="https://res.cloudinary.com/millermayhem/image/upload/v1653982722/Gallery_Placeholder_rjvxg5.jpg"
                                class="card-img-top" style="opacity: 0.5;" alt="Booking card with shop image and logo">
                            <div class="card-body">
                                <h5 class="card-title">{{ booking.date }}</h5>
                                <p class="card-text">Your nails appointment is at:<br>{{ booking.time }}</p>
                                <td>
                                    <a href="/edit/{{ booking.id }}" type="edit" class="btn btn-secondary">Edit
                                    </a>
                                </td>
                                <td>
                                    <a href="/delete/{{ booking.id }}" type="button" class="btn btn-danger"
                                            onclick="return confirm('Are you sure you want to delete your booking?');">Delete
                                    </a>
                                </td>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="container appointment-container">
    <div class="">
        <a href="{% url 'appointment_bookings' %}" type="button" class="btn btn-outline-secondary page-button"
            style="margin-top: 30px;">Make Booking</a>
    </div>
</div>

{% endif %}

{% endblock %}

templates/prices.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col memory-title">
      Nails worth every penny!
    </div>
  </div>
</div>

<div class="container">
  <a href="">
    <img class="prices-image"
      src="https://res.cloudinary.com/millermayhem/image/upload/v1654711187/Price_List_Back_Hannahs_Nov_2021-01_w5dpib.png"
      alt="Hannahs nail bar price list">
  </a>
</div>

{% endblock %}